### ISSUE TITLE
Page contents seem to reload 1-2 times on opening the homepage

### ISSUE THREAD

**Issue by arjun27** [covid-maps/covid-maps#214]
Experience is jarring and needs a fix. `getStateFromProps` seems to be the suspect.

**Comment by arjun27** [comment]
Updated diagnosis - it's happening due to the reload in service worker updates @preetjdp

**Comment by preetjdp** [comment]
We should remove the `window.reload` but this will require to manually reload the site to get newer changes (But since people tend to refresh webpages frequently, this should not be a problem).

https://github.com/covid-maps/covid-maps/blob/c820ff45c5c98699a39a205f7d8eb188550c955a/src/index.js#L32

Lemme know what you think.

**Comment by arjun27** [comment]
sounds better than what we have currently
